Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # height_in and weight_lb are available as a regular lists
... 
... # Import numpy
... import numpy as np
... 
... # Calculate the BMI: bmi
... np_height_m = np.array(height_in) * 0.0254
... np_weight_kg = np.array(weight_lb) * 0.453592
... bmi = np_weight_kg / np_height_m ** 2
... 
... # Create the light array
... light = bmi < 21
... 
... 
... 
... # Print out light
... print(light)
... 
... # Print out BMIs of all baseball players whose BMI is below 21
