Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> # heights and positions are available as lists
... 
... # Import numpy
... import numpy as np
... 
... # Convert positions and heights to numpy arrays: np_positions, np_heights
... np_positions = np.array(positions)
... np_heights = np.array(heights)
... 
... 
... # Heights of the goalkeepers: gk_heights
... gk_heights = np_heights[np_positions == 'GK']
... 
... # Heights of the other players: other_heights
... other_heights = np_heights[np_positions != 'GK']
... 
... # Print out the median height of goalkeepers. Replace 'None'
... print("Median height of goalkeepers: " + str(np.median(gk_heights)))
... 
... # Print out the median height of other players. Replace 'None'
